"""
Django settings for djangocelery project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import djcelery
from celery.schedules import timedelta
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zgvq)=zp!@w@rh%b!3g=4@*c57fn9=rat5#3#etb7v()i6olx9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]
import django_crontab

# Application definition
INSTALLED_APPS = [
    'django_crontab',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.app1.apps.App1Config',
    'apps.app2.apps.App2Config',
    'djcelery',
    'rest_framework',



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangocelery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangocelery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djangocelery',
        'USER': 'root',
        'HOST': 'localhost',
        'PASSWORD': 'root',
        # 'PASSWORD': '1234567',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/True

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# 当djcelery.setup_loader()运行时，Celery便会去查看INSTALLD_APPS下包含的所有app目录中的tasks.py文件，
# 找到标记为task的方法，将它们注册为celery task。
djcelery.setup_loader()  # 对配置进行加载

BROKER_URL = 'redis://127.0.0.1:6379/0'             # broker是代理人，它负责分发任务给worker去执行
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'  # 后端，用于存储任务执行结果，推荐redis

CELERY_TASK_SERIALIZER = 'json'                     # 任务的序列化方式
CELERY_RESULT_SERIALIZER = 'json'                   # 任务执行结果的序列化方式
CELERY_ACCEPT_CONTENT = ['json']                    # 指定任务接受的内容序列化类型(序列化)，一个列表；
CELERY_IMPORTS = ('app1.tasks', )                    # 定义任务所在的模块
CELERY_TIMEZONE = 'Asia/Shanghai'                   # 时区设置，计划任务需要，推荐 Asia/Shanghai
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERYD_CONCURRENCY = 3                             # worker并发数   任务消费者的并发数
CELERYD_PREFETCH_MULTIPLIER = 1  # 每个worker 领取一个任务
# CELERYD_FORCE_EXECV = True
CELERYD_MAX_TASKS_PER_CHILD = 100  # 每个worker最多执行玩100个任务就会被销毁，可防止内存泄露



# CELERY_FORCE_EXECV = True# 有些情况可以防止死锁
# CELERY_QUEUES # Celery队列设定
CELERY_TASK_RESULT_EXPIRES = 50 # 60 * 60 * 24   # 任务结果的过期时间，在上边设置的redis中
# 规定完成任务的时间
# CELERYD_TASK_TIME_LIMIT = 5 #15 * 60 # 在15分钟内完成任务，否则执行该任务的worker将被杀死，任务移交给父进程

# BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3} # 任务发出后，经过一段时间还未收到acknowledge , 就将任务重新交给其他worker执行


# celery的定时任务都是有celery beat来进行调度，celery beat默认按照settings.py之中的时区时间来调度定时任务。
# celery 创建定时任务  Celery计划任务设定
CELERYBEAT_SCHEDULE = {
    # 定时任务一：　每隔s运行一次
    'task1': {
        # "task": "apps.orders.tasks.order_to_mission",
        "task": "app1.tasks.add",
        "schedule": timedelta(seconds=5),
        "args": (100, 200),
    },
    # 定时任务二：　每隔s运行一次
    'task2': {
        "task": "app1.tasks.add1",
        "schedule": timedelta(seconds=1),
        "args": (10, 20),
    },
}

from django.core.management.base import BaseCommand


CRONJOBS = [
    # ('*/1 * * * *', 'app名.定时函数所在的py文件名.定时函数名', '>> 输出文件路径和名称')
    # 每1分钟执行restart_pm2函数，并将执行中的返回的内容全部打印到crontab.log文件中
    ('*/1 * * * *', 'app1.tasks.restart_pm2', '>>/home/wangzhipeng/myproject/crontab.log'),

    # 每1分钟执行django的自定义命令，并将执行中的返回的内容全部打印到crontab.log文件中
    ('*/1 * * * *', 'django.core.management.call_command', ['mycommand1'], {"param": "mycommand1_test"}, '>>/home/wangzhipeng/myproject/crontab.log'),
    ('*/1 * * * *', 'django.core.management.call_command', ['mycommand2'], {"param": "mycommand2_test"}, '>>/home/wangzhipeng/myproject/crontab.log')
]



# RESTFRAMEWORK 认证配置参数,全剧设置
REST_FRAMEWORK = {
    # 认证的全局配置
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # 'apps.app1.utils.auth.FirstAuthtication',
        # 'apps.app1.utils.auth.Authtication',
    ),

    # 权限的全局配置
    # "DEFAULT_PERMISSION_CLASSES": [
    #     'apps.app1.utils.permissions.Mypermission',
    #     'apps.app1.utils.permissions.Mypermission2',
    # ],

    # 访问频率的控制--自定义频率限制类
    'DEFAULT_THROTTLE_CLASSES': (
        # 'apps.app1.utils.throttle.VisitThrottle',
        # 'apps.app1.utils.throttle.VisitThrottle2',
        # 'apps.app1.utils.throttle.UserThrottle',

    ),

    # Throttling,访问频率的控制--设定访问频率的相关参数
    'DEFAULT_THROTTLE_RATES': {
        'wzp': "5/m",  # 表示1分钟内只允许访问3次   wzp仅代表一个键名字  源码中会根据scope中所赋值来决定的，然后来获取rate=4/m  缓存中
        'wzp01': "7/m",
        'user': None,
        'anon': None,
    },

    """以下是restframework中的get方法传递版本参数的配置参数"""  
    'DEFAULT_VERSION': "v1", # 默认版本v1
    'ALLOWED_VERSIONS': ["v1","v2"], # 表示允许的版本只有v1，v2
    'VERSION_PARAM': "version",# 设置url中参数的关键字    比如：http://127.0.0.1:8000/?version==v1中的version为前边设置的字符串

    # """以下是restframework中的通过url路径来传递版本参数的配置方法"""
    # "DEFAULT_VERSIONING_CLASS": 'rest_framework.versioning.URLPathVersioning',

    # 每页显示两条数据
    'PAGE_SIZE': 2,


}


# 日志文件
BASE_LOG_DIR = os.path.join(os.path.dirname(BASE_DIR), "logs")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {  # 配置打印日志格式
        'standard': {  # name:记录器的名称  lineo:执行日志记录调用的行号 module:执行日志记录调用的模块名称 funcName:模块中调用的函数  levelname：日志级别
            'format': '%(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d] [%(module)s:%(funcName)s] [%(levelname)s]- %(message)s'}
        # 日志格式
    },

    # 'filters': {  # 过滤器   # 控制哪些日志可以从logger流向Handler
    #     'require_debug_true': {
    #         '()': 'django.utils.log.RequireDebugTrue',
    #     },
    # },

    'handlers': {  # 用来定义具体处理日志的方式(规定日志输出到哪里)，可以定义多种，"default"就是默认方式，"console"就是打印到控制台方式
        'default': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',  # 会根据文件大小自动切
            'filename': os.path.join(BASE_LOG_DIR, "warning.log"),  # 日志输出文件名称
            'maxBytes': 1024 * 1024 * 5,  # 文件大小
            'backupCount': 5,  # 备份份数
            'formatter': 'standard',  # 使用哪种formatters日志格式
        },
        'error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_LOG_DIR, "error.log"),
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'standard',
        },
        'request_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_LOG_DIR, "debug.log"),
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'standard',
        },
        # # 在终端打印
        # 'console': {
        #     'level': 'DEBUG',
        #     'filters': ['require_debug_true'],  # 只有在Django debug为True时才在屏幕打印日志
        #     'class': 'logging.StreamHandler',  #
        #     'formatter': 'simple'
        # },
    },

    'loggers': {  # LOGGER记录器,配置用那种handlers来处理日志，比如你同时需要输出日志到文件、控制台。----logger传递日志到handler
        # 以下三个为django基本需要的记录器，尽量不要动

        # ‘’ 日志实例对象默认配置（需要'disable_existing_loggers': False才能生效）,此时在别的模块中使用logger_default = logging.getLogger(__name__),记录器的名称为该模块的名称，并使用default处理器来处理日志
        '': {
            'handlers': ['default'],
            'level': 'DEBUG',
            'propagate': False  # 向不向更高级别的logger传递
        },

        'django': {  # 若将对应的handler中的level等级改为DEBUG，那么会在日志文件中把所有的信息打印出来，包括对数据库的操作（前提是django开启的是DEBUG模式！！）
            'handlers': ['default'],
            'level': 'DEBUG',
            'propagate': False  # 向不向更高级别的logger传递
        },

        'django.request': {  # 这个记录器用于记录django框架里面的所有request请求的记录，名称必须为django.request！！！！
            'handlers': ['request_handler'],
            'level': 'DEBUG',
            'propagate': False,
        },


        # 下面自定义记录器
        'views_error': {  #
            'handlers': ['default', 'error', 'request_handler'],  # 会根据三个handler中日志的等级，在其对应的日志文件中进行打印
            'level': 'DEBUG',
            'propagate': True
        },

    },

}


